# Generated by Django 5.0.1 on 2024-01-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.CharField(choices=[('A', 'Em aberto'), ('C', 'Concluido')], default='A', max_length=1),
        ),
    ]
